### ISSUE TITLE
Grid no longer compiles with Intel compiler 17.0.0 on KNL

### ISSUE THREAD

**Issue by giltirn** [paboyle/Grid#139] opened 2018-01-03 17:10 UTC
I'm using

bash-4.2$ mpiicpc --version
icpc (ICC) 17.0.0 20160721
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.

(Is this ICPC version not included in the compiler test suite?)

with the following compile options:

```
../../src/Grid/configure CXX=mpiicpc CC=mpiicc --enable-simd=KNL --prefix=/home/ckelly/knl/install_mpi LDFLAGS="" --enable-precision=single --enable-timers=yes --enable
-mkl --enable-comms=mpi --disable-silent-rules --with-fftw="/home/ckelly/knl/install_base_mpi" CXXFLAGS="-g" LDFLAGS="-g"
```

Most of the errors appear to be associated with ET functions involving ComplexF and vTComplexD.

I've checked both the current head (67c3fa0f5f2adda473b7543121a7ad6041547259) and an older commit from Dec 11 (2401360784cc57f63501dca993f912d12ed73bcd). The errors are as follows:

```
bash-4.2$ make
Making all in lib
make[1]: Entering directory `/home/ckelly/knl/bld/grid/lib'
make  all-am
make[2]: Entering directory `/home/ckelly/knl/bld/grid/lib'
depbase=`echo qcd/action/fermion/WilsonFermion.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
mpiicpc -DHAVE_CONFIG_H -I. -I../../../src/Grid/lib    -I/home/ckelly/knl/src/Grid/include -xmic-avx512 -I/home/ckelly/knl/install_base_mpi/include -fopenmp  -O3 -g -std=c++11 -MT qcd/action/fermion/WilsonFermion.o -MD -MP -MF $depbase.Tpo -c -o qcd/action/fermion/WilsonFermion.o ../../../src/Grid/lib/qcd/action/fermion/WilsonFermion.cc &&\
mv -f $depbase.Tpo $depbase.Po
/home/ckelly/knl/src/Grid/include/Grid/lattice/Lattice_ET.h(263): error: more than one operator "*" matches these operands:
            function "std::operator*(const std::complex<float> &, const std::complex<float> &)"
            function template "Grid::iScalar<l> Grid::operator*(Grid::iScalar<l>::scalar_type, const Grid::iScalar<l> &)"
            function template "Grid::iScalar<l> Grid::operator*(Grid::ComplexD, const Grid::iScalar<l> &)"
            operand types are: const Grid::ComplexF * const Grid::QCD::vTComplexD
  GridBinOpClass(BinaryMul, lhs *rhs);
  ^
          detected during:
            instantiation of class "Grid::BinaryMul<left, right> [with left=Grid::ComplexF, right=const Grid::QCD::vTComplexD &]" at line 101 of "/usr/include/c++/4.8.5/bits/stl_pair.h"
            instantiation of class "std::pair<_T1, _T2> [with _T1=Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, _T2=std::tuple<const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>]" at line 75 of "/home/ckelly/knl/src/Grid/include/Grid/lattice/Lattice_base.h"
            instantiation of class "Grid::LatticeBinaryExpression<Op, T1, T2> [with Op=Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, T1=const std::complex<float> &, T2=const Grid::Lattice<Grid::QCD::vTComplexD> &]" at line 408 of "../../../src/Grid/lib/qcd/action/fermion/WilsonFermion.cc"
            instantiation of "void Grid::QCD::WilsonFermion<Impl>::SeqConservedCurrent(Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::Current, unsigned int, std::vector<Grid::Real={Grid::RealF={float}}, std::allocator<Grid::Real={Grid::RealF={float}}>>, unsigned int, unsigned int) [with Impl=Grid::QCD::WilsonImplD]" at line 454 of "../../../src/Grid/lib/qcd/action/fermion/WilsonFermion.cc"

/home/ckelly/knl/src/Grid/include/Grid/lattice/Lattice_ET.h(248): error: no instance of overloaded function "Grid::exp" matches the argument list
            argument types are: (const Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>)
  GridUnopClass(UnaryExp, exp(a));
  ^
/home/ckelly/knl/src/Grid/include/Grid/lattice/Lattice_ET.h(384): note: this candidate was rejected because function is not visible
  GRID_DEF_UNOP(exp, UnaryExp);
  ^
/home/ckelly/knl/src/Grid/include/Grid/tensors/Tensor_unary.h(92): note: this candidate was rejected because at least one template argument could not be deduced
  UNARY(exp);
  ^
/home/ckelly/knl/src/Grid/include/Grid/tensors/Tensor_unary.h(92): note: this candidate was rejected because at least one template argument could not be deduced
  UNARY(exp);
  ^
/home/ckelly/knl/src/Grid/include/Grid/tensors/Tensor_unary.h(92): note: this candidate was rejected because at least one template argument could not be deduced
  UNARY(exp);
  ^
/home/ckelly/knl/src/Grid/include/Grid/simd/Grid_vector_unops.h(160): note: this candidate was rejected because at least one template argument could not be deduced
  inline Grid_simd<S, V> exp(const Grid_simd<S, V> &r) {
                         ^
/usr/include/bits/mathcalls.h(100): note: this candidate was rejected because arguments do not match
  __MATHCALL (exp,, (_Mdouble_ __x));
  ^
/usr/include/c++/4.8.5/bits/valarray_after.h(452): note: this candidate was rejected because at least one template argument could not be deduced
      _DEFINE_EXPR_UNARY_FUNCTION(exp, _Exp)
      ^
/usr/include/c++/4.8.5/bits/valarray_after.h(452): note: this candidate was rejected because at least one template argument could not be deduced
      _DEFINE_EXPR_UNARY_FUNCTION(exp, _Exp)
      ^
/usr/include/c++/4.8.5/complex(756): note: this candidate was rejected because at least one template argument could not be deduced
      exp(const complex<_Tp>& __z) { return __complex_exp(__z.__rep()); }
      ^
/usr/include/c++/4.8.5/cmath(253): note: this candidate was rejected because at least one template argument could not be deduced
      exp(_Tp __x)
      ^
/usr/include/c++/4.8.5/cmath(245): note: this candidate was rejected because arguments do not match
    exp(long double __x)
    ^
/usr/include/c++/4.8.5/cmath(241): note: this candidate was rejected because arguments do not match
    exp(float __x)
    ^
/usr/include/c++/4.8.5/cmath(237): note: this candidate was rejected because arguments do not match
    using ::exp;
            ^
          detected during:
            instantiation of class "Grid::UnaryExp<arg> [with arg=Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>]" at line 101 of "/usr/include/c++/4.8.5/bits/stl_pair.h"
            instantiation of class "std::pair<_T1, _T2> [with _T1=Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>>, _T2=std::tuple<const Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &> &>]" at line 69 of
                      "/home/ckelly/knl/src/Grid/include/Grid/lattice/Lattice_base.h"
            instantiation of class "Grid::LatticeUnaryExpression<Op, T1> [with Op=Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>>, T1=const Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &> &]" at line 408 of
                      "../../../src/Grid/lib/qcd/action/fermion/WilsonFermion.cc"
            instantiation of "void Grid::QCD::WilsonFermion<Impl>::SeqConservedCurrent(Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::Current, unsigned int, std::vector<Grid::Real={Grid::RealF={float}}, std::allocator<Grid::Real={Grid::RealF={float}}>>, unsigned int, unsigned int) [with Impl=Grid::QCD::WilsonImplD]" at line 454 of "../../../src/Grid/lib/qcd/action/fermion/WilsonFermion.cc"

/home/ckelly/knl/src/Grid/include/Grid/lattice/Lattice_base.h(126): error: no suitable user-defined conversion from "Grid::LatticeUnaryExpression<Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>>, const Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const
          Grid::Lattice<Grid::QCD::vTComplexD> &> &>" to "Grid::QCD::vTComplexD" exists
        vobj tmp = eval(ss,expr);
                   ^
          detected during:
            instantiation of "Grid::Lattice<vobj> &Grid::Lattice<vobj>::operator=(const Grid::LatticeUnaryExpression<Op, T1> &) [with vobj=Grid::QCD::vTComplexD, Op=Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>>, T1=const Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const
                      Grid::Lattice<Grid::QCD::vTComplexD> &> &]" at line 408 of "../../../src/Grid/lib/qcd/action/fermion/WilsonFermion.cc"
            instantiation of "void Grid::QCD::WilsonFermion<Impl>::SeqConservedCurrent(Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::Current, unsigned int, std::vector<Grid::Real={Grid::RealF={float}}, std::allocator<Grid::Real={Grid::RealF={float}}>>, unsigned int, unsigned int) [with Impl=Grid::QCD::WilsonImplD]" at line 454 of "../../../src/Grid/lib/qcd/action/fermion/WilsonFermion.cc"

compilation aborted for ../../../src/Grid/lib/qcd/action/fermion/WilsonFermion.cc (code 2)
make[2]: *** [qcd/action/fermion/WilsonFermion.o] Error 2
make[2]: Leaving directory `/home/ckelly/knl/bld/grid/lib'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/ckelly/knl/bld/grid/lib'
make: *** [all-recursive] Error 1
```

Antonin edit: style for readability

**Comment by paboyle** [comment] 2018-01-08 15:45
I reproduced it on the KNL Ninja system here.

The corresponding icpc 2017 build on "TeamCity" from NERSC succeeded.

https://ci.cliath.ph.ed.ac.uk/viewLog.html?buildId=7437&buildTypeId=Grid_Avx_Intel17&tab=buildLog&_focus=720#_state=79,158,589

However, TeamCity appears to have no AVX512 builds running?

We need to have a discussion about TeamCity coverage.

There's too many old GCC versions, and not enough of selecting between MPI, non-MPI and
architecture (AVX512, SSE) coverage.

**Comment by aportelli** [comment] 2018-01-08 21:14
Consolidating the CI is a long overdue item in my todo list. I will make it my highest priority now, I agree cleaning is needed. I have an idea on what to do, but it would be useful to have some feedback on what would be needed. For example:

1. Which compilers do we want to systematically test?
2. What tests need to be run?
3. Is there anything special that need to be check for MPI (e.g. various topologies, special tests, etc...)?

**Comment by paboyle** [comment] 2018-01-09 22:01
Agree; but I think email issues will be inefficient.
Either a software call, or some session in front of a blackboard with interested parties will converge faster and waste our deciding time less.

Lets figure a convenient time and form a plan.

**Comment by giltirn** [comment] 2018-01-12 20:33
Any idea how to fix the compile issue? Unfortunately it is preventing me from compiling and testing the new MPI implementations on Hokusai also (Intel compile 17.0.4).

**Comment by aportelli** [comment] 2018-01-13 12:46
@giltirn I cannot reproduce the issue. This works just fine on my KNL with the Intel compiler version you indicated (17.0.4).

Looking at your log I cannot see an error message which is directly related to the SIMD option choice. However, I can guess through some messages that you are using the Intel compiler with the GCC 4.8 binding which is very likely to fail considering that Grid is not compatible with this version of GCC. I don't say it is related to the problem but this is something different to the setup I used which binds to GCC 6.2.

I have setup 2 KNL configurations in the CI for Intel 2017 & 2018. Have a look at https://ci.cliath.ph.ed.ac.uk for more details (give it some time to run I just did it). Btw, I noticed you are not registered there, I would encourage you to do it if you want some notifications that code you push is breaking something.

**Comment by aportelli** [comment] 2018-01-13 15:11
Working ICPC 17.0.4 KNL build
https://ci.cliath.ph.ed.ac.uk/viewLog.html?buildId=7720&buildTypeId=Grid_Knl_Intel17&tab=buildResultsDiv

**Comment by giltirn** [comment] 2018-01-16 18:16
Unfortunately I'm still having the same problem despite using gcc 6.3.0:

[ckelly@hokusai2 grid]$ mpiicpc -v
mpiicpc for the Intel(R) MPI Library 2017 Update 3 for Linux*
Copyright(C) 2003-2017, Intel Corporation.  All rights reserved.
icpc version 17.0.4 (gcc version 6.3.0 compatibility)

Error:

depbase=`echo qcd/action/fermion/WilsonFermion.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
mpiicpc -DHAVE_CONFIG_H -I. -I/bwfefs/home/ckelly/src/grid/Grid/lib    -I/bwfefs/home/ckelly/src/grid/Grid/include -xcore-avx512 -fopenmp  -O3  -MT qcd/action/fermion/WilsonFermion.o -MD -MP -MF $depbase.Tpo -c -o qcd/action/fermion/WilsonFermion.o /bwfefs/home/ckelly/src/grid/Grid/lib/qcd/action/fermion/WilsonFermion.cc &&\
mv -f $depbase.Tpo $depbase.Po
/bwfefs/home/ckelly/src/grid/Grid/include/Grid/lattice/Lattice_ET.h(263): error: more than one operator "*" matches these operands:
            function "std::operator*(const std::complex<float> &, const std::complex<float> &)"
            function template "Grid::iScalar<l> Grid::operator*(Grid::iScalar<l>::scalar_type, const Grid::iScalar<l> &)"
            function template "Grid::iScalar<l> Grid::operator*(Grid::ComplexD, const Grid::iScalar<l> &)"
            operand types are: const Grid::ComplexF * const Grid::QCD::vTComplexD
  GridBinOpClass(BinaryMul, lhs *rhs);
  ^
          detected during:
            instantiation of class "Grid::BinaryMul<left, right> [with left=Grid::ComplexF, right=const Grid::QCD::vTComplexD &]" at line 195 of "/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/bits/stl_pair.h"
            instantiation of class "std::pair<_T1, _T2> [with _T1=Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, _T2=std::tuple<const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>]" at line 75 of "/bwfefs/home/ckelly/src/grid/Grid/include/Grid/lattice/Lattice_base.h"
            instantiation of class "Grid::LatticeBinaryExpression<Op, T1, T2> [with Op=Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, T1=const std::complex<float> &, T2=const Grid::Lattice<Grid::QCD::vTComplexD> &]" at line 408 of "/bwfefs/home/ckelly/src/grid/Grid/lib/qcd/action/fermion/WilsonFermion.cc"
            instantiation of "void Grid::QCD::WilsonFermion<Impl>::SeqConservedCurrent(Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::Current, unsigned int, std::vector<Grid::Real={Grid::RealF={float}}, std::allocator<Grid::Real={Grid::RealF={float}}>>, unsigned int, unsigned int) [with Impl=Grid::QCD::WilsonImplD]" at line 454 of "/bwfefs/home/ckelly/src/grid/Grid/lib/qcd/action/fermion/WilsonFermion.cc"

/bwfefs/home/ckelly/src/grid/Grid/include/Grid/lattice/Lattice_ET.h(248): error: no instance of overloaded function "Grid::exp" matches the argument list
            argument types are: (const Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>)
  GridUnopClass(UnaryExp, exp(a));
  ^
/bwfefs/home/ckelly/src/grid/Grid/include/Grid/lattice/Lattice_ET.h(384): note: this candidate was rejected because function is not visible
  GRID_DEF_UNOP(exp, UnaryExp);
  ^
/bwfefs/home/ckelly/src/grid/Grid/include/Grid/tensors/Tensor_unary.h(92): note: this candidate was rejected because at least one template argument could not be deduced
  UNARY(exp);
  ^
/bwfefs/home/ckelly/src/grid/Grid/include/Grid/tensors/Tensor_unary.h(92): note: this candidate was rejected because at least one template argument could not be deduced
  UNARY(exp);
  ^
/bwfefs/home/ckelly/src/grid/Grid/include/Grid/tensors/Tensor_unary.h(92): note: this candidate was rejected because at least one template argument could not be deduced
  UNARY(exp);
  ^
/bwfefs/home/ckelly/src/grid/Grid/include/Grid/simd/Grid_vector_unops.h(160): note: this candidate was rejected because at least one template argument could not be deduced
  inline Grid_simd<S, V> exp(const Grid_simd<S, V> &r) {
                         ^
/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/math.h(49): note: this candidate was rejected because arguments do not match
  using std::exp;
             ^
/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/math.h(49): note: this candidate was rejected because arguments do not match
  using std::exp;
             ^
/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/math.h(49): note: this candidate was rejected because at least one template argument could not be deduced
  using std::exp;
             ^
/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/math.h(49): note: this candidate was rejected because at least one template argument could not be deduced
  using std::exp;
             ^
/usr/include/bits/mathcalls.h(100): note: this candidate was rejected because arguments do not match
  __MATHCALL (exp,, (_Mdouble_ __x));
  ^
/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/bits/valarray_after.h(452): note: this candidate was rejected because at least one template argument could not be deduced
      _DEFINE_EXPR_UNARY_FUNCTION(exp, _Exp)
      ^
/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/bits/valarray_after.h(452): note: this candidate was rejected because at least one template argument could not be deduced
      _DEFINE_EXPR_UNARY_FUNCTION(exp, _Exp)
      ^
/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/complex(761): note: this candidate was rejected because at least one template argument could not be deduced
      exp(const complex<_Tp>& __z) { return __complex_exp(__z.__rep()); }
      ^
/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/cmath(257): note: this candidate was rejected because at least one template argument could not be deduced
      exp(_Tp __x)
      ^
/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/cmath(249): note: this candidate was rejected because arguments do not match
    exp(long double __x)
    ^
/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/cmath(245): note: this candidate was rejected because arguments do not match
    exp(float __x)
    ^
/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/cmath(241): note: this candidate was rejected because arguments do not match
    using ::exp;
            ^
          detected during:
            instantiation of class "Grid::UnaryExp<arg> [with arg=Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>]" at line 195 of "/bwfefs/opt/x86_64/gcc/6.3.0/include/c++/6.3.0/bits/stl_pair.h"
            instantiation of class "std::pair<_T1, _T2> [with _T1=Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>>, _T2=std::tuple<const Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &> &>]" at line 69 of
                      "/bwfefs/home/ckelly/src/grid/Grid/include/Grid/lattice/Lattice_base.h"
            instantiation of class "Grid::LatticeUnaryExpression<Op, T1> [with Op=Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>>, T1=const Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &> &]" at line 408 of
                      "/bwfefs/home/ckelly/src/grid/Grid/lib/qcd/action/fermion/WilsonFermion.cc"
            instantiation of "void Grid::QCD::WilsonFermion<Impl>::SeqConservedCurrent(Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::Current, unsigned int, std::vector<Grid::Real={Grid::RealF={float}}, std::allocator<Grid::Real={Grid::RealF={float}}>>, unsigned int, unsigned int) [with Impl=Grid::QCD::WilsonImplD]" at line 454 of "/bwfefs/home/ckelly/src/grid/Grid/lib/qcd/action/fermion/WilsonFermion.cc"

/bwfefs/home/ckelly/src/grid/Grid/include/Grid/lattice/Lattice_base.h(126): error: no suitable user-defined conversion from "Grid::LatticeUnaryExpression<Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>>, const Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const
          Grid::Lattice<Grid::QCD::vTComplexD> &> &>" to "Grid::QCD::vTComplexD" exists
        vobj tmp = eval(ss,expr);
                   ^
          detected during:
            instantiation of "Grid::Lattice<vobj> &Grid::Lattice<vobj>::operator=(const Grid::LatticeUnaryExpression<Op, T1> &) [with vobj=Grid::QCD::vTComplexD, Op=Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>>, T1=const Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::ComplexF, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const
                      Grid::Lattice<Grid::QCD::vTComplexD> &> &]" at line 408 of "/bwfefs/home/ckelly/src/grid/Grid/lib/qcd/action/fermion/WilsonFermion.cc"
            instantiation of "void Grid::QCD::WilsonFermion<Impl>::SeqConservedCurrent(Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::WilsonFermion<Impl>::PropagatorField &, Grid::QCD::Current, unsigned int, std::vector<Grid::Real={Grid::RealF={float}}, std::allocator<Grid::Real={Grid::RealF={float}}>>, unsigned int, unsigned int) [with Impl=Grid::QCD::WilsonImplD]" at line 454 of "/bwfefs/home/ckelly/src/grid/Grid/lib/qcd/action/fermion/WilsonFermion.cc"

compilation aborted for /bwfefs/home/ckelly/src/grid/Grid/lib/qcd/action/fermion/WilsonFermion.cc (code 2)
make[2]: *** [qcd/action/fermion/WilsonFermion.o] Error 2
make[2]: Leaving directory `/bwfefs/home/ckelly/bld/grid/lib'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/bwfefs/home/ckelly/bld/grid/lib'
make: *** [all-recursive] Error 1
[ckelly@hokusai2 grid]$

**Comment by coppolachan** [comment] 2018-01-17 12:02
Looks like Intel 17 because I retried on the KNL box (Peter's) and enabled gcc 6.3 by doing
scl enable devtoolset-6 bash    (valid on CentOS)

[cossu@knlpaboyle GridKNL_Single]$ icpc -v
icpc version 17.0.1 (gcc version 6.3.1 compatibility)

but I am getting the same error reported by Chris.

**Comment by aportelli** [comment] 2018-01-17 13:29
I do not have the issue with Intel 17 on my KNL, cf. CI. The errors are about operator overloading in the expression template engine. There was no recent changes to this part of the code so if there was a problem with Intel 17 we would know it since a long time.

I still believe it is a build configuration issue, but now that we see that unfortunately it is not just the GCC binding we need to dig more. @giltirn could you provide the complete `configure` command and its output please?

**Comment by aportelli** [comment] 2018-01-17 13:42
Ok reading between the lines we might not use the same precision setting, I use `double`. I started a build https://ci.cliath.ph.ed.ac.uk/viewLog.html?buildId=7865&buildTypeId=Grid_Knl_Intel17&tab=buildLog with `single` to see if it reproduces your error.

**Comment by aportelli** [comment] 2018-01-17 13:43
It does... so at least we know what triggers it. We have to investigate more. But double precision builds just look fine.

**Comment by coppolachan** [comment] 2018-01-17 13:50
Latest commit should solve the problem. I am compiling right now.

**Comment by coppolachan** [comment] 2018-01-17 15:07
I confirm that the latest commit compiles on Peter's KNL box. The problem should be solved.
Why the problem appears only for the AVX512 is still under investigation.

**Comment by coppolachan** [comment] 2018-01-18 10:31
I retract my last comment: the problem appears with Intel 17 and it is NOT related to the AVX512 only, I just recompiled the code (forcing the bug) for AVX2 and I get the same error. This is reassuring in the sense that now the path is clear.
I am suggesting that Andrew have a deep look at all his routines and do not mix the default precision variables defined in QCD.h with the precision of the Wilson operator (that depends on the template).
I can be of support for this change but I will not do myself.

**Comment by aportelli** [comment] 2018-01-18 11:24
Andrew is not working with us anymore. These are just the conserved currents methods, Wilson and DWF, if you know how to fix one cleanly the other should take you 5sec.

**Comment by paboyle** [comment] 2018-03-08 13:13
Interestingly I just hit a compiler bug on Cori with Intel 17.0.2 with a very simple signature in CayleyFermion5Dcache.cc (introduced code that tickles the bug, and worked around in the feature/gpu-port).

Not hit present on 17.0.3 and 18.0.1, g++ (any version) or clang++ or nvcc.....

**Comment by giltirn** [comment] 2018-08-27 21:41
This issue appears to persist on Intel 18.0.2 and gcc 6.4.0 in the latest development code. Workaround is still to compile with precision=double.  I believe we discussed removing the concept of a default precision from the library; I expect that if this were to happen any such bugs would immediately become apparent.

**Comment by paboyle** [comment] 2018-08-27 21:44
You sure it is the same problem. Someone committed crap code that is hardwired to double, that is causing the CI server to fail, and never fixed it.

**Comment by paboyle** [comment] 2018-08-27 21:46
i..e it was immeditately apparent. It failed and the CI server emailed about it.

**Comment by aportelli** [comment] 2018-08-28 19:02
This is, I believe, now fixed in `develop`. @giltirn please let us know if you still have issues.

**Comment by giltirn** [comment] 2019-02-21 16:30
Sorry for dropping the ball on this Antonin. I just checked with the latest dev build and I am still getting the same errors:

/home/ckelly/knl/src/Grid/Grid/lattice/Lattice_base.h(148): error: no suitable user-defined conversion from "const Grid::LatticeBinaryExpression<Grid::BinaryMul<Grid::iScalar<Grid::iVector<Grid::iVector<Grid::vComplexD, 8>, 4>>, Grid::LatticeUnaryExpression<Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<std::complex<float>, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>>, const
          Grid::LatticeBinaryExpression<Grid::BinaryMul<std::complex<float>, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &> &>>, const Grid::iScalar<Grid::iVector<Grid::iVector<Grid::vComplexD, 8>, 4>> &, const Grid::LatticeUnaryExpression<Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<std::complex<float>, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>>, const
          Grid::LatticeBinaryExpression<Grid::BinaryMul<std::complex<float>, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &> &> &>" to "Grid::iScalar<Grid::iVector<Grid::iVector<Grid::vComplexD, 8>, 4>>" exists
        vobj tmp = eval(ss,expr);
                   ^
          detected during:
            instantiation of "Grid::Lattice<vobj> &Grid::Lattice<vobj>::operator=(const Grid::LatticeBinaryExpression<Op, T1, T2> &) [with vobj=Grid::iScalar<Grid::iVector<Grid::iVector<Grid::vComplexD, 8>, 4>>, Op=Grid::BinaryMul<const Grid::iScalar<Grid::iVector<Grid::iVector<Grid::vComplexD, 8>, 4>> &, Grid::LatticeUnaryExpression<Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<std::complex<float>, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const
                      Grid::Lattice<Grid::QCD::vTComplexD> &>>, const Grid::LatticeBinaryExpression<Grid::BinaryMul<std::complex<float>, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &> &>>, T1=const Grid::Lattice<Grid::iScalar<Grid::iVector<Grid::iVector<Grid::vComplexD, 8>, 4>>> &, T2=const Grid::LatticeUnaryExpression<Grid::UnaryExp<Grid::LatticeBinaryExpression<Grid::BinaryMul<std::complex<float>, const Grid::QCD::vTComplexD &>, const
                      std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &>>, const Grid::LatticeBinaryExpression<Grid::BinaryMul<std::complex<float>, const Grid::QCD::vTComplexD &>, const std::complex<float> &, const Grid::Lattice<Grid::QCD::vTComplexD> &> &> &]" at line 123 of "/home/ckelly/knl/src/Grid/Grid/qcd/action/fermion/FermionOperator.h"
            instantiation of "void Grid::QCD::FermionOperator<Impl>::FreePropagator(const Grid::QCD::FermionOperator<Impl>::FermionField &, Grid::QCD::FermionOperator<Impl>::FermionField &, Grid::RealD={double}, std::vector<double, std::allocator<double>>) [with Impl=Grid::QCD::WilsonAdjImplD]" 

and many more like it. I'm using

mpiicpc for the Intel(R) MPI Library 2018 Update 2 for Linux*
Copyright(C) 2003-2018, Intel Corporation.  All rights reserved.
icpc version 18.0.2 (gcc version 6.4.0 compatibility)

and Grid dev branch commit e37614bde4aaf0822f00306cf766bb02b1a6b50a (Feb 14th). Fix still appears to be to compile in double-precision mode.

**Comment by paboyle** [comment] 2019-03-27 22:55
I think fixed 2018 - please try

**Comment by paboyle** [comment] 2020-05-11 21:16
Close as I thought fixed?

**Closed** 2020-05-12 23:55 UTC
