### ISSUE TITLE
Intel Compilation Error

### ISSUE THREAD

**Issue by sidkashyap** [paboyle/Grid#26] opened 2016-02-24 17:19 UTC
We get the following error when we try to compile Grid on Intel

In file included from ../../../lib/qcd/action/Actions.h(44),
                 from ../../../lib/qcd/QCD.h(460),
                 from ../../../lib/Grid.h(78),
                 from ../../../lib/PerfCount.cc(29):
/usr/include/c++/5/bits/stl_iterator_base_types.h(154): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::iterator_category iterator_category;

Please find attached the full list of errors
_______________

$ icpc --version
icpc (ICC) 16.0.0 20150815
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.

$ g++ --version
g++ (Ubuntu 5.1.1-4ubuntu12) 5.1.1 20150504
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO

[build_out.txt](https://github.com/paboyle/Grid/files/145075/build_out.txt)
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by rprollins** [comment] 2016-03-03 17:27
I found this: [https://software.intel.com/en-us/forums/intel-c-compiler/topic/565143](https://software.intel.com/en-us/forums/intel-c-compiler/topic/565143)

In summary, a fix to the GCC 5.0 C++11 headers wasn't reflected by Intel compilers until version 16.0.2.

I have compiled with Intel 16.0.1 and GCC  4.9.1 but reproduce the error when switching to GCC 5.1.1.

Does anyone have Intel 16.0.2 and GCC 5.x to test and confirm the fix?

**Comment by paboyle** [comment] 2016-03-30 07:32
Indeed looks like icpc is choking on recent GCC headers.

NERSC is at 16.0.0. 

I have access to 16.0.2 on a system somewhere, but the GCC versions
are opaque -- labelled "5.x-20150310" which doesn't seem to be a versioned
GCC release.

Will give it a go if I get time, but also looks like the sort of problem that is easier to "wait out".

**Comment by paboyle** [comment] 2016-04-16 10:50
Suggesting to close this. I've got night compiles running on NERSC under ICC 16 and 4.9.3, and this
is really a problem of G++ vs. Intel which is supposedly resolved in 16.0.2.

**Closed by paboyle** 2016-04-16 10:50 UTC
