### ISSUE TITLE
Segmentation fault with Benchmark_wilson

### ISSUE THREAD

**Issue by i-kanamori** [paboyle/Grid#30] opened 2016-04-21 08:52 UTC
Dear contributers,

I tried to run benchmarks, but Benchmark_wilson failed due to Segmentation fault.
Benchmark_dwf and Benchmark_zmm seem to have the same problem.
I am not sure this is a problem of Grid or gcc behind the intel compiler.

version of the Grid:
master, as of Apr. 21 (d9b5e66877066c1ac65bc3846b3321ee6ac2e29b)

$ ./Benchmark_wilson --debug-signals

__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
__|__|  |  |  |  |  |  |  |  |  |  |  | _|__
__|__                                   _|__
__|_   GGGG    RRRR    III    DDDD      _|__
__|_  G        R   R    I     D   D     _|__
__|_  G        R   R    I     D    D    _|__
__|_  G  GG    RRRR     I     D    D    _|__
__|_  G   G    R  R     I     D   D     _|__
__|_   GGGG    R   R   III    DDDD      _|__
__|__                                   _|__
__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
  |  |  |  |  |  |  |  |  |  |  |  |  |  |

Copyright (C) 2015 Peter Boyle, Azusa Yamaguchi, Guido Cossu, Antonin Portelli and other authors
Colours by Tadahito Boyle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Grid : Message    : 0 ms : Grid is setup to use 1 threads
Grid : Message    : 0 ms : Grid floating point word size is REALF4
Grid : Message    : 0 ms : Grid floating point word size is REALD8
Grid : Message    : 0 ms : Grid floating point word size is REAL4
Grid : Message    : 1134 ms : Calling Dw
Caught signal 11
  mem address 4
         code 1
  instruction 3c4c20e0fc
  rdi 77af20
  rsi 0
  rbp 0
  rbx 0
  rdx 22088400
  rax 0
  rcx 20
  rsp 7ffc40e26ed0
  rip 3c4c20e0fc
  r8 2eb4a67
  r9 0
  r10 7ffc40e26d40
  r11 7ffc40e26cf0
  r12 3c56cefa88
  r13 0
  r14 13c65c0
  r15 0
BackTrace Strings: 0 ./Benchmark_wilson() [0x4366da]
BackTrace Strings: 1 /lib64/libc.so.6() [0x3c4ca326a0]
BackTrace Strings: 2 /lib64/ld-linux-x86-64.so.2() [0x3c4c20e0fc]
BackTrace Strings: 3 /lib64/ld-linux-x86-64.so.2() [0x3c4c2148f5]
BackTrace Strings: 4 /usr/lib64/libstdc++.so.6(_ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEE+0x97) [0x3c56ab65a7]
BackTrace Strings: 5 ./Benchmark_wilson() [0x441170]
BackTrace Strings: 6 ./Benchmark_wilson() [0x46c105]
BackTrace Strings: 7 ./Benchmark_wilson() [0x46c045]
BackTrace Strings: 8 ./Benchmark_wilson() [0x487d8e]
BackTrace Strings: 9 ./Benchmark_wilson() [0x487d00]
BackTrace Strings: 10 ./Benchmark_wilson() [0x48761b]
BackTrace Strings: 11 ./Benchmark_wilson() [0x406cbd]
BackTrace Strings: 12 /lib64/libc.so.6(__libc_start_main+0xfd) [0x3c4ca1ed5d]
BackTrace Strings: 13 ./Benchmark_wilson() [0x4032c9]

---------------------------------------
Here is my configuration:

$ ../configure CXX=icpc --enable-simd=AVX --enable-precision=single CXXFLAGS="-std=c++11 -O0 -debug inline-debug-info -g " --enable-comms=none

$ icpc -v
icpc version 16.0.1 (gcc version 4.8.2 compatibility)

The build gave plenty of warnings, like:

../../lib/simd/Grid_avx.h(521): warning #167: argument of type "__m128" is incompatible with parameter of type "__m128i"
        _mm256_alignr_epi32(ret,in,tmp,n);
        ^
          detected during instantiation of "__m256 Grid::Optimization::Rotate::tRotate<n>(__m256) [with n=0]" at line 494

../../lib/simd/Grid_avx.h(521): warning #167: argument of type "__m128" is incompatible with parameter of type "__m128i"
        _mm256_alignr_epi32(ret,in,tmp,n);
        ^
          detected during instantiation of "__m256 Grid::Optimization::Rotate::tRotate<n>(__m256) [with n=0]" at line 494

../../lib/simd/Grid_avx.h(521): warning #167: argument of type "__m128i" is incompatible with parameter of type "const __m128 &"
        _mm256_alignr_epi32(ret,in,tmp,n);
        ^
          detected during instantiation of "__m256 Grid::Optimization::Rotate::tRotate<n>(__m256) [with n=0]" at line 494

(it continues for about 48000 lines)

The machine has an Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz, which has the AVX,
and 16GB memory.

Other benchmarks:

OK:
Benchmark_su3
Benchmark_memory_asynch
Benchmark_memory_bandwidth

Failed:
Benchmark_comms : Aborted (due to --enable-comms=none, I guess)
Benchmark_dwf   : Segmentation fault (after "Calling Dw")
Benchmark_zmm   : Segmentation fault (after "Calling Dw")

Best regards,

Issaku

**Comment by paboyle** [comment] 2016-04-29 21:43
Thanks -- I've reproduced this.

**Comment by paboyle** [comment] 2016-04-29 22:03
For info -- I'm seeing it working under Clang and ICPC, but failing under G++ on Cori.

Amusingly, there is a bug in gdb on Cori that makes gdb itself segv when it reads the symbols in 
the debug binary which is a pain...  Apparently an infinite recursion loop on detangling C++11 symbols.

gdb gdb

**Comment by paboyle** [comment] 2016-04-29 23:50
Hmm... it's associated with the use of std::thread in the comms overlapped with compute
portion.

I can disable this -- it went slower rather than faster on the Cray hardware I was targeting.

However, for now it does look to me like GCC's fault and not mine.  I've committed a patch,
simply switching off the use of std::thread()

Peter

**Comment by i-kanamori** [comment] 2016-04-30 09:54
Thank you very much, I have confirmed that the new version runs without any problems.
I actually had the same problem with  Clang 3.5, but has disappeared now.

The latest version also runs with more realistic configurations with icpc: 
 + without the debug option: CXX=icpc --enable-simd=AVX --enable-precision=single CXXFLAGS="-std=c++11 -O3 -mavx" LIBS="-lgmp -lmpfr" --enable-comms=none
 + with openmp: CXX=icpc --enable-simd=AVX --enable-precision=single CXXFLAGS="-fopenmp -std=c++11 -O3 -mavx " LIBS="-lgmp -lmpfr" --enable-comms=none
 + with openmp and mpi:  CXX=mpic++ --enable-simd=AVX --enable-precision=single CXXFLAGS="-fopenmp -std=c++11 -O3 -mavx " LIBS="-lgmp -lmpfr" --enable-comms=mpi
   ( my environment for the mpi is open MPI 1.10.2) 

Issaku

**Comment by paboyle** [comment] 2016-04-30 10:07
Thanks Issaku,

I will now return to the IMCI compilation.

Peter

**Comment by paboyle** [comment] 2016-04-30 10:57
From Babbage at NERSC.

[pboyle@bint01 icpc-imci-none]$ icpc --version
icpc (ICC) 16.0.0 20150815
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.

[pboyle@bint01 icpc-imci-none]$ gcc (GCC) 4.8.0


 $ ../../configure --host=none --enable-precision=single --enable-simd=IMCI CXXFLAGS=-mmic -openmp -O3 -std=c++11 LDFLAGS= LIBS=-mmic -openmp --enabl
e-comms=none CXX=icpc

Clean compile:
make[1]: Entering directory `/chos/global/u1/p/pboyle/nightly/Grid/builds/icpc-imci-none/benchmarks'
  CXX    Benchmark_comms.o
  CXX    Benchmark_dwf.o
  CXX    Benchmark_memory_asynch.o
  CXX    Benchmark_memory_bandwidth.o
  CXX    Benchmark_su3.o
  CXX    Benchmark_wilson.o
  CXX    Benchmark_zmm.o
  CXXLD  Benchmark_comms
  CXXLD  Benchmark_su3
  CXXLD  Benchmark_memory_bandwidth
  CXXLD  Benchmark_memory_asynch
  CXXLD  Benchmark_zmm
  CXXLD  Benchmark_dwf
  CXXLD  Benchmark_wilson

**Comment by paboyle** [comment] 2016-04-30 11:02
Also an aside on clang-3.5 -- Clang only integrated openMP into the main trunk on v3.8 .

I think, but don't know clang-omp++, the non-standard OpenMP development branch would have
been ok on 3.5, but not stock 3.5. 

I've been using clang 3.8 since it was released since it was the first clang with OMP support
integrated in the main branch.

**Comment by i-kanamori** [comment] 2016-05-02 04:22
I will try the new version with KNC, although I have no time till Friday.  Also I will update my Clang to 3.8.  
Thank you very much,
Issaku

**Comment by i-kanamori** [comment] 2016-05-06 09:12
Now the latest version (Grid-f8f9fd6f22aede4c78284b912bee0ae79d68fb3c) runs on KNC, thank you very much.

../configure CXX=icpc --enable-simd=IMCI --enable-precision=single  CXXFLAGS="-fast -mmic -fopenmp -std=c++11 -I/opt/mic/include/" LDFLAGS="-mmic" LIBS="-mmic -L/opt/mic/lib -lmpfr -lgmp"  --enable-comms=none --host=none
(I also tried -O0 and -O3 instead of -fast, all of them works)

**Closed** 2016-06-03 12:34 UTC
