### ISSUE TITLE
INDICATIVE BENCHMARK RESULTS

### ISSUE THREAD

**Issue by derekrattansey** [paboyle/Grid#322] opened 2020-10-30 13:19 UTC
INDICATIVE BENCHMARK RESULTS
As an aid to bidders we document indicative single node and single device results for those architectures we have had benchmark access to. Multi-node results will be dictated by MPI network efficiency of the vendors network.
Nvida Ampere: We have obtained 2600GFlop/s on Juelich Booster with one A100, and a single node (4 GPUs) delivers up to 8000GFlop/s (with NVlink used).
Nvidia Volta: We have obtained 1600 Gflop/s with one V100 on ORNL Summit and a single node (6 GPUs) delivers up 6000Gflop/s (with NVlink used).
AMD MI-50: We have obtained up to 670Gflop/s from one MI-50.
AMD Rome: We have obtained up to 1.9TFlop/s from two socket Rome (128 cores).
Intel Skylake: We have obtained up to 520 Gflop/s from two socket Skylake 8170. We do not have results for more recent parts but note that these are three years old.

My questions:

•	For which benchmark are these indicative results? We are assuming this is Benchmark_ITT and not SOMBRERO?
•	Appreciate if you can share any example output files?

**Comment by paboyle** [comment] 2020-10-30 18:24
Hi, thanks

Intended to be indicative for Benchmark_ITT.

Due to piecemeal/temporary access to customer login nodes etc... we've not been able to run the frozen Benchmark_ITT on all these architectures.

Most of these are with Benchmark_dwf_fp32, but this is the same routine that is called for the comparison point
in Benchmark_ITT.

What differs potentially is the volume on which the problem is run.

**1. Nvidia Ampere:** 

obtained on Booster@Juelich. A range of high figures were obtained (in fact up to 8.9TF/s) but these were not specifically the volumes used in Benchmark_ITT. I should be able to run the Benchmark_ITT over the weekend, but there are no guarantees as the machine has been under maintenance and is under construction. This is a reasonable endeavours effort.

Confidence in our indicative figure: Good. (it could be less than 8000, but it will be roughly correct).

**2. Nvidia Volta**

Benchmark_dwf has performed slightly better than Benchmark_ITT (less freedom of choice on volume). 
We have obtained a run log on Summit and placed it on GitHub [here:](https://github.com/paboyle/Grid/wiki/Benchmark_ITT:-Example-output).

Confidence in our indicative figure: High

**2. MI-50** : obtained with Benchmark_dwf. This should translate to Benchmark_ITT, but this was only a single GPU run, and the scaling across GPU's is unknown.

Confidence in our indicative figure: High for 1 GPU

3. Rome

This was Benchmark_dwf on a 16^3x32 volume per socket. Summary slides of the two day hackathon when we
had Rome access are [here:](https://github.com/paboyle/Grid/wiki/Benchmark_ITT:-Example-output)

Benchmark_ITT pushes the volume from 8^4 to 32^4 and a cache effect is likely at larger volumes. 

Confidence in our indicative figure: low - there is likely a cache effect for larger volumes.

4. Intel Skylake 

Full dual socket Skylake 4116 Silver results (12+12 cores) are placed on the Wiki (same location as above).

**Comment by paboyle** [comment] 2020-12-18 15:02
closing

**Closed by paboyle** 2020-12-18 15:02 UTC
