### ISSUE TITLE
Compilation fails for simple configure [SOLVED]

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#108] opened 2017-05-19 15:15 UTC
(Thanks to Nils Meyer for pointing this)
```
$ ./bootstrap.sh
$ ./configure
$ make
```

fails in the current devel and release 0.7.0, 0.6.0
Errors coming from Eigen
```
In file included from /home/neo/Codes/Grid/include/Grid/Eigen/Core:470:0,
                 from /home/neo/Codes/Grid/include/Grid/Eigen/Dense:1,
                 from /home/neo/Codes/Grid/include/Grid/Grid_Eigen_Dense.h:6,
                 from /home/neo/Codes/Grid/include/Grid/lattice/Lattice_reduction.h:25,
                 from /home/neo/Codes/Grid/include/Grid/lattice/Lattice_base.h:339,
                 from /home/neo/Codes/Grid/include/Grid/lattice/Lattice.h:31,
                 from /home/neo/Codes/Grid/include/Grid/GridCore.h:54,
                 from ../../../Grid/lib/stencil/Lebesgue.cc:29:
/home/neo/Codes/Grid/include/Grid/Eigen/src/Core/products/GeneralBlockPanelKernel.h:450:88: error: macro "acc" requires 5 arguments, but only 3 given
   EIGEN_STRONG_INLINE void acc(const AccPacket& c, const ResPacket& alpha, ResPacket& r) const
                                                                                        ^
In file included from /home/neo/Codes/Grid/include/Grid/Eigen/Core:470:0,
                 from /home/neo/Codes/Grid/include/Grid/Eigen/Dense:1,
                 from /home/neo/Codes/Grid/include/Grid/Grid_Eigen_Dense.h:6,
                 from /home/neo/Codes/Grid/include/Grid/lattice/Lattice_reduction.h:25,
                 from /home/neo/Codes/Grid/include/Grid/lattice/Lattice_base.h:339,
                 from /home/neo/Codes/Grid/include/Grid/lattice/Lattice.h:31,
                 from /home/neo/Codes/Grid/include/Grid/GridCore.h:54,
                 from ../../../Grid/lib/stencil/Stencil.cc:28:
/home/neo/Codes/Grid/include/Grid/Eigen/src/Core/products/GeneralBlockPanelKernel.h:450:88: error: macro "acc" requires 5 arguments, but only 3 given
   EIGEN_STRONG_INLINE void acc(const AccPacket& c, const ResPacket& alpha, ResPacket& r) const
...............
```

**Comment by aportelli** [comment] 2017-05-19 15:22
I cannot reproduce that, neither does the CI. Sounds like mixed Eigen install. I am removing the bug tag unless we can establish that this is not a bad configuration on the build platform.

**Comment by aportelli** [comment] 2017-05-19 15:24
Or did you mean that we should be able to use Grid with `configure` without options?

**Comment by aportelli** [comment] 2017-05-19 15:29
Ok got it without arguments. I don't think this is Eigen, it looks more that the half-precision implementation broke the generic SIMD

```
In file included from ../../../../../../lib/perfmon/PerfCount.cc:29:
In file included from /Users/antonin/Development/Grid/include/Grid/GridCore.h:47:
In file included from /Users/antonin/Development/Grid/include/Grid/simd/Simd.h:175:
In file included from /Users/antonin/Development/Grid/include/Grid/simd/Grid_vector_types.h:42:
/Users/antonin/Development/Grid/include/Grid/simd/Grid_generic.h:296:14: error: use of undeclared identifier 'ret'
      return ret;
             ^
In file included from ../../../../../../lib/allocator/AlignedAllocator.cc:4:
In file included from /Users/antonin/Development/Grid/include/Grid/GridCore.h:47:
In file included from /Users/antonin/Development/Grid/include/Grid/simd/Simd.h:175:
In file included from /Users/antonin/Development/Grid/include/Grid/simd/Grid_vector_types.h:42:
/Users/antonin/Development/Grid/include/Grid/simd/Grid_generic.h:296:14: error: use of undeclared identifier 'ret'
      return ret;
             ^
In file included from ../../../../../../lib/algorithms/approx/MultiShiftFunction.cc:28:
In file included from /Users/antonin/Development/Grid/include/Grid/GridCore.h:47:
In file included from /Users/antonin/Development/Grid/include/Grid/simd/Simd.h:175:
In file included from /Users/antonin/Development/Grid/include/Grid/simd/Grid_vector_types.h:42:
/Users/antonin/Development/Grid/include/Grid/simd/Grid_generic.h:296:14: error: use of undeclared identifier 'ret'
      return ret;
             ^
In file included from ../../../../../../lib/perfmon/Stat.cc:1:
In file included from /Users/antonin/Development/Grid/include/Grid/GridCore.h:47:
In file included from /Users/antonin/Development/Grid/include/Grid/simd/Simd.h:175:
In file included from /Users/antonin/Development/Grid/include/Grid/simd/Grid_vector_types.h:42:
/Users/antonin/Development/Grid/include/Grid/simd/Grid_generic.h:296:14: error: use of undeclared identifier 'ret'
      return ret;
             ^
```

**Comment by coppolachan** [comment] 2017-05-19 15:31
I am committing the solution in minutes.

**Comment by aportelli** [comment] 2017-05-19 15:32
What I can see is that `USE_FP16` is supposed to be `SW_FP16`, is that what you're doing?

**Comment by coppolachan** [comment] 2017-05-19 15:35
There are two things,
undeclaring the acc macro

and taking care of the ret in the precision, that means either exposing the definition of ret or hiding the return ret here
```  
 static inline vech StoH (const vecf &a,const vecf &b) {
   
#ifdef USE_FP16
      vech ret;
   vech *ha = (vech *)&a;
      vech *hb = (vech *)&b;
      const int nf = W<float>::r;
      //      VECTOR_FOR(i, nf,1){ ret.v[i]    = ( (uint16_t *) &a.v[i])[1] ; }
      //      VECTOR_FOR(i, nf,1){ ret.v[i+nf] = ( (uint16_t *) &b.v[i])[1] ; }
      VECTOR_FOR(i, nf,1){ ret.v[i]    = ha->v[2*i+1]; }
      VECTOR_FOR(i, nf,1){ ret.v[i+nf] = hb->v[2*i+1]; }
#else
      assert(0);
#endif
      return ret;
    }
  
```

 What do you prefer?

**Comment by aportelli** [comment] 2017-05-19 15:38
I did not write this part on FP16 so I am not sure (Peter did?). My opinion would be to move `vech ret;` outside of the `#ifdef block` as I am not really sure that non-returning non-throwing functions with a return type are part of the standard.

**Comment by aportelli** [comment] 2017-05-19 15:39
What's wrong with `acc`? Eigen 3.3.3 compiles fine with other SIMD options I was thinking this is a consequence of this previous error.

**Comment by coppolachan** [comment] 2017-05-19 15:41
Committed the fix

**Comment by coppolachan** [comment] 2017-05-19 15:42
acc macro is defined in that Grid_generic.h file but is not undefined. 
there is an acc function in Eigen that complains about that.

**Comment by coppolachan** [comment] 2017-05-19 15:42
I undefined accordingly, when not used anymore and fixed the problem with the ret.

**Comment by coppolachan** [comment] 2017-05-19 15:57
Reopening as we should consider probably moving this fix to 0.7.0.
Let me know your thoughts.

**Comment by paboyle** [comment] 2017-05-19 21:16
I'd say a 0.7.1 release is wise.

I'm VERY much against revising releases after the fact. Generic is NOT normally used, and people who
report a subsequent issue on 0.7.0 have then an ambiguous version.

**Comment by paboyle** [comment] 2017-05-19 21:18
I've been thinking a 0.7.1 is wise of a BG/Q update. Perhaps a couple of weeks timescale.
We could add the generic patch to that, and think about splitting an incremental from which 0.8.0
milestones can wait.

**Comment by aportelli** [comment] 2017-05-19 22:07
I am also against moving releases, that's what hotfixes are for. We could wait BG/Q for 0.7.1, or do it now and have a 0.7.2 for BG/Q. I am happy with both.

**Comment by paboyle** [comment] 2017-05-19 22:08
Agree. I'm cool with either. Let's do what is pragmatic.

**Comment by paboyle** [comment] 2017-05-24 21:21
Perhaps now we understand Andrew's BG/Q regression problem as just a likely boundary condition mismatch the effort in getting BG/Q working again is an order of magnitude smaller.

**Comment by paboyle** [comment] 2017-06-22 19:11
Perhaps we leave this in develop, migrates to next release and can close the issue?

**Closed** 2017-07-13 23:27 UTC
Labels: bug
